spring:
  data:
    mongodb:
      uri: mongodb+srv://posterProj:cWcc6JGnf8UlUtOe@postersatbrown.dtqiuai.mongodb.net/
      database: postersatbrown
  security:
    user:
      name: posters
      password: brown
  logging:
    level:
      org:
        springframework:
          web: DEBUG

